apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: resilient-observability

# Build configuration for custom apps
build:
  artifacts:
    - image: app1-producer
      context: apps/app1
      docker:
        dockerfile: Dockerfile
    - image: app2-consumer
      context: apps/app2
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true

# Raw manifests for Kafka cluster and apps
manifests:
  rawYaml:
    - manifests/kafka-cluster.yaml
    - manifests/apps.yaml

# Deploy configuration using Helm
deploy:
  helm:
    releases:
    # Loki - Log aggregation
    - name: loki
      repo: https://grafana.github.io/helm-charts
      remoteChart: loki
      namespace: loki
      createNamespace: true
      valuesFiles:
        - helm/loki-values.yaml
      wait: true
      upgradeOnChange: true

    # Tempo - Distributed tracing
    - name: tempo
      repo: https://grafana.github.io/helm-charts
      remoteChart: tempo
      version: 1.18.1
      namespace: tempo
      createNamespace: true
      valuesFiles:
        - helm/tempo-values.yaml
      wait: true
      upgradeOnChange: true

    # Mimir - Metrics storage
    - name: mimir
      repo: https://grafana.github.io/helm-charts
      remoteChart: mimir-distributed
      namespace: mimir
      createNamespace: true
      valuesFiles:
        - helm/mimir-values.yaml
      wait: true
      upgradeOnChange: true

    # OpenTelemetry Collector
    - name: opentelemetry-collector
      repo: https://open-telemetry.github.io/opentelemetry-helm-charts
      remoteChart: opentelemetry-collector
      version: 0.80.1
      namespace: opentelemetry
      createNamespace: true
      valuesFiles:
        - helm/otel-collector-values.yaml
      wait: true
      upgradeOnChange: true

    # Strimzi Kafka Operator
    - name: strimzi-kafka-operator
      repo: https://strimzi.io/charts/
      remoteChart: strimzi-kafka-operator
      namespace: strimzi
      createNamespace: true
      valuesFiles:
        - helm/strimzi-values.yaml
      wait: true
      upgradeOnChange: true

    # Grafana - Visualization (deployed last)
    - name: grafana
      repo: https://grafana.github.io/helm-charts
      remoteChart: grafana
      version: 8.12.1
      namespace: grafana
      createNamespace: true
      valuesFiles:
        - helm/grafana-values.yaml
      wait: true
      upgradeOnChange: true

# Port forwarding for local access
portForward:
  - resourceType: service
    resourceName: grafana
    namespace: grafana
    port: 80
    localPort: 3000

  - resourceType: service
    resourceName: loki-gateway
    namespace: loki
    port: 80
    localPort: 3100

  - resourceType: service
    resourceName: tempo
    namespace: tempo
    port: 3100
    localPort: 3200

  - resourceType: service
    resourceName: mimir-query-frontend
    namespace: mimir
    port: 8080
    localPort: 9009

  - resourceType: service
    resourceName: opentelemetry-collector
    namespace: opentelemetry
    port: 4317
    localPort: 4317

  - resourceType: service
    resourceName: opentelemetry-collector
    namespace: opentelemetry
    port: 4318
    localPort: 4318

  - resourceType: service
    resourceName: app1-producer
    namespace: apps
    port: 80
    localPort: 8080

  - resourceType: service
    resourceName: app2-consumer
    namespace: apps
    port: 80
    localPort: 8081

# Profiles for different scenarios
profiles:
  # Minimal profile - just Grafana + Loki
  - name: minimal
    deploy:
      helm:
        releases:
        - name: loki
          repo: https://grafana.github.io/helm-charts
          remoteChart: loki
          namespace: loki
          createNamespace: true
          valuesFiles:
            - helm/loki-values.yaml

        - name: grafana
          repo: https://grafana.github.io/helm-charts
          remoteChart: grafana
          version: 8.12.1
          namespace: grafana
          createNamespace: true
          valuesFiles:
            - helm/grafana-values.yaml

    portForward:
      - resourceType: service
        resourceName: grafana
        namespace: grafana
        port: 80
        localPort: 3000

      - resourceType: service
        resourceName: loki-gateway
        namespace: loki
        port: 80
        localPort: 3100

  # Infrastructure only - observability stack + kafka without apps
  - name: infra
    build:
      artifacts: []
    manifests:
      rawYaml:
        - manifests/kafka-cluster.yaml
    deploy:
      helm:
        releases:
        - name: loki
          repo: https://grafana.github.io/helm-charts
          remoteChart: loki
          namespace: loki
          createNamespace: true
          valuesFiles:
            - helm/loki-values.yaml
          wait: true

        - name: tempo
          repo: https://grafana.github.io/helm-charts
          remoteChart: tempo
          version: 1.18.1
          namespace: tempo
          createNamespace: true
          valuesFiles:
            - helm/tempo-values.yaml
          wait: true

        - name: mimir
          repo: https://grafana.github.io/helm-charts
          remoteChart: mimir-distributed
          namespace: mimir
          createNamespace: true
          valuesFiles:
            - helm/mimir-values.yaml
          wait: true

        - name: opentelemetry-collector
          repo: https://open-telemetry.github.io/opentelemetry-helm-charts
          remoteChart: opentelemetry-collector
          version: 0.80.1
          namespace: opentelemetry
          createNamespace: true
          valuesFiles:
            - helm/otel-collector-values.yaml
          wait: true

        - name: strimzi-kafka-operator
          repo: https://strimzi.io/charts/
          remoteChart: strimzi-kafka-operator
          namespace: strimzi
          createNamespace: true
          valuesFiles:
            - helm/strimzi-values.yaml
          wait: true

        - name: grafana
          repo: https://grafana.github.io/helm-charts
          remoteChart: grafana
          version: 8.12.1
          namespace: grafana
          createNamespace: true
          valuesFiles:
            - helm/grafana-values.yaml
          wait: true

    portForward:
      - resourceType: service
        resourceName: grafana
        namespace: grafana
        port: 80
        localPort: 3000

      - resourceType: service
        resourceName: loki-gateway
        namespace: loki
        port: 80
        localPort: 3100

      - resourceType: service
        resourceName: tempo
        namespace: tempo
        port: 3100
        localPort: 3200

      - resourceType: service
        resourceName: mimir-query-frontend
        namespace: mimir
        port: 8080
        localPort: 9009

      - resourceType: service
        resourceName: opentelemetry-collector
        namespace: opentelemetry
        port: 4317
        localPort: 4317

      - resourceType: service
        resourceName: opentelemetry-collector
        namespace: opentelemetry
        port: 4318
        localPort: 4318

# Verify deployments
verify:
  - name: loki-ready
    container:
      name: loki-check
      image: curlimages/curl:latest
      command: ["curl"]
      args: ["-f", "http://loki-gateway.loki.svc.cluster.local/ready"]

  - name: grafana-ready
    container:
      name: grafana-check
      image: curlimages/curl:latest
      command: ["curl"]
      args: ["-f", "http://grafana.grafana.svc.cluster.local/api/health"]
